#!/bin/sh

set -e
if [ purge = "$1" ]
then

	if [ -f /etc/logrotate.d/powertweak ]
		then rm -f /etc/logrotate.d/powertweak; 
	fi
	if [ -f /var/log/powertweak ]
		then rm -f /var/log/powertweak*; 
	fi
	if [ -f /etc/powertweak.config ]
		then rm -f /etc/powertweak.config; 
	fi
fi

#DEBHELPER#
