.TH powertweak 8 "27 Dec 2000" "powertweak"
.SH NAME
powertweak \- text mode tool to configure hardware tweaks for powertweakd
.SH SYNOPSIS
.B powertweak
.RI [ options ]

.SH DESCRIPTION
This manual page documents briefly the
.B powertweak
command.

powertweak is the text interface to choose the kind of hardware
tweaks that you want the powertweakd daemon to perform on your system.
The options must be self explanatory.

This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.

.SH FILES
.BR /etc/powertweak.config

.SH AUTHOR
This manual page was written by Sudhakar Chandrasekharan
 <thaths@netscape.com>,
for the Debian GNU/Linux system (but may be used by others).
